name: Build Go Executable

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v7.0.1

    - name: Set up Go
      uses: actions/setup-go@v7.0.0
      with:
        go-version: '1.22'

    - name: Get current date and time
      run: |
        echo "DATE=$(Get-Date -Format 'yyyyMMdd')" >> $env:GITHUB_ENV
        echo "DATETIME=$(Get-Date -Format 'yyyy-MM-dd HH:mm')" >> $env:GITHUB_ENV
        echo "TAGNAME=v$(Get-Date -Format 'yyyyMMdd-HHmmss')" >> $env:GITHUB_ENV

    - name: Build Windows Executable
      run: |
        go build -o mesnevi.exe main.go memory.go

    - name: Upload Artifact
      uses: actions/upload-artifact@v7.0.1
      with:
        name: mesnevi-${{ env.DATE }}
        path: mesnevi.exe

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v3.0.3
      with:
        tag_name: ${{ env.TAGNAME }}
        name: Build ${{ env.DATETIME }}
        body: ${{ env.DATETIME }}
        files: mesnevi.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
